name: zhalbyrak
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.20.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  fluttertoast: ^9.0.0
  firebase_storage: ^13.0.4
  image_picker: ^1.2.1
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2
  shared_preferences: ^2.2.3

  cloud_functions: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: ArialBlack
      fonts:
        - asset: assets/fonts/arial_black.ttf

  assets:
    - assets/secom_logo.png
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon/app_icon.png


flutter_native_splash:
  android: true
  ios: true

  color: "#FFFFFF"
  color_dark: "#FFFFFF"

  image: assets/icon/quokka.png
  image_dark: assets/icon/quokka.png

  android_gravity: center
  ios_content_mode: center

  android_12:
    image: assets/icon/quokka.png
    image_dark: assets/icon/quokka.png
    color: "#FFFFFF"
    color_dark: "#FFFFFF"

