// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkZoWLttwhP4ynlG5vU0YUYFdXYALBG2A',
    appId: '1:174257410842:web:1b825c35e1748db0d252a3',
    messagingSenderId: '174257410842',
    projectId: 'secom-f3642',
    authDomain: 'secom-f3642.firebaseapp.com',
    storageBucket: 'secom-f3642.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJKDIb9fsfs3vSHEJ8qkPhMtq6mhVJf-8',
    appId: '1:174257410842:android:a5c350df2407bb8ed252a3',
    messagingSenderId: '174257410842',
    projectId: 'secom-f3642',
    storageBucket: 'secom-f3642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmZul5VTxoll9jXdHFjalAUobgLYt86Lc',
    appId: '1:174257410842:ios:c3186ab57f68c5f2d252a3',
    messagingSenderId: '174257410842',
    projectId: 'secom-f3642',
    storageBucket: 'secom-f3642.firebasestorage.app',
    iosBundleId: 'com.example.secom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmZul5VTxoll9jXdHFjalAUobgLYt86Lc',
    appId: '1:174257410842:ios:c3186ab57f68c5f2d252a3',
    messagingSenderId: '174257410842',
    projectId: 'secom-f3642',
    storageBucket: 'secom-f3642.firebasestorage.app',
    iosBundleId: 'com.example.secom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkZoWLttwhP4ynlG5vU0YUYFdXYALBG2A',
    appId: '1:174257410842:web:cb4fb09f4dad56f1d252a3',
    messagingSenderId: '174257410842',
    projectId: 'secom-f3642',
    authDomain: 'secom-f3642.firebaseapp.com',
    storageBucket: 'secom-f3642.firebasestorage.app',
  );

}